workflows:
  expo-android-build:
    name: Expo Android Build
    max_build_duration: 120
    environment:
      node: 18.17.1
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          yarn global add @expo/cli turtle-cli
          yarn install
          
      - name: Expo prebuild and build
        script: |
          # Login to Expo
          npx expo login --token $EXPO_TOKEN
          
          # Prebuild the native code
          npx expo prebuild --platform android
          
          # Build APK locally
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/apk/**/*.apk
    
    publishing:
      email:
        recipients:
          - deamirclothingstores@gmail.com
        notify:
          success: true
          failure: true