workflows:
  expo-android-build:
    name: EAS Android Build
    max_build_duration: 120
    environment:
      node: 18.17.1
      # EAS CLI will handle all the build environment setup
    scripts:
      - name: Install EAS CLI and dependencies
        script: |
          # Install EAS CLI globally
          npm install -g eas-cli
          
          # Install project dependencies
          npm install
          
          # Login to Expo (using environment variable)
          # Make sure to set EXPO_TOKEN in Codemagic environment variables
          eas login --token $EXPO_TOKEN
          
      - name: Build with EAS
        script: |
          # Build the APK using EAS
          eas build -p android --profile production --non-interactive --no-wait
          
          # The build will be handled by Expo's servers
          echo "Build started! Check your Expo dashboard for progress and download link."
          echo "You'll receive an email when the build is complete."
    
    # No need to specify artifacts as EAS will handle the build output
    
    publishing:
      email:
        recipients:
          - deamirclothingstores@gmail.com
        notify:
          success: true
          failure: true
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true