workflows:
  expo-android-build:
    name: Expo Android Build with Upload
    max_build_duration: 120
    environment:
      node: 18.20.0
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          pip3 install setuptools
          npm cache clean --force
          npm install
          npm install -g @expo/cli
          
      - name: Build APK
        script: |
          # Check login status
          npx expo whoami || echo "Not logged in"
          
          # Login if token available
          if [ ! -z "$EXPO_TOKEN" ]; then
            echo "$EXPO_TOKEN" | npx expo login --stdin
          fi
          
          # Prebuild
          npx expo prebuild --platform android
          
          # Check if android folder exists
          if [ -d "android" ]; then
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease
            
            # Copy APK to easy location
            if ls app/build/outputs/apk/release/*.apk 1> /dev/null 2>&1; then
              cp app/build/outputs/apk/release/*.apk ../my-app.apk
              echo "APK created successfully!"
            else
              echo "APK build failed or not found"
              find . -name "*.apk" -type f
              exit 1
            fi
          else
            echo "Android folder not created"
            exit 1
          fi
          
      - name: Upload APK to file sharing
        script: |
          # Upload to transfer.sh (free file sharing)
          echo "Uploading APK to transfer.sh..."
          curl --upload-file my-app.apk https://transfer.sh/my-app.apk
          echo ""
          
          # Also try uploading to 0x0.st
          echo "Uploading to 0x0.st..."
          curl -F'file=@my-app.apk' https://0x0.st
          echo ""
          
          # Show file info
          ls -la my-app.apk
          
    artifacts:
      - my-app.apk
      - android/app/build/outputs/apk/release/*.apk
    
    publishing:
      email:
        recipients:
          - deamirclothingstores@gmail.com
        notify:
          success: true
          failure: true