workflows:
  android-workflow:
    name: Android Build with Expo
    max_build_duration: 120
    environment:
      vars:
        # Using debug keystore for simplicity
        KEYSTORE_PASSWORD: android
        KEY_ALIAS: androiddebugkey
        KEY_PASSWORD: android
      node: 18.17.1  # Specify Node.js version to avoid compatibility issues
    scripts:
      - name: Set up environment
        script: |
          # Check if pnpm is already available, if not install it
          if ! command -v pnpm &> /dev/null; then
            npm install -g pnpm --force
          fi
          
          # Install project dependencies
          pnpm install
          
          # Skip EAS setup since no EXPO_TOKEN is provided
          echo "Building locally without Expo cloud services"
          
      - name: Set up debug keystore
        script: |
          # Create keystore properties for debug
          echo "storeFile=debug.keystore" > android/keystore.properties
          echo "storePassword=android" >> android/keystore.properties
          echo "keyAlias=androiddebugkey" >> android/keystore.properties
          echo "keyPassword=android" >> android/keystore.properties
          
          # The debug.keystore will be automatically generated by Gradle
          
      - name: Build Android Release
        script: |
          # Use the local build script from package.json
          pnpm run build:android:local
          
      - name: Upload Artifact
        script: |
          mkdir -p build
          cp android/app/build/outputs/bundle/release/app-release.aab build/
          cp android/app/build/outputs/apk/release/app-release.apk build/
    artifacts:
      - build/*.apk
      - build/*.aab
    publishing:
      email:
        recipients:
          - your.email@example.com  # Update with your email
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true