workflows:
  expo-android-build:
    name: Simple Expo Android Build
    max_build_duration: 120
    environment:
      node: 18.17.1
      java: 11
    scripts:
      - name: Install and setup
        script: |
          # Install Expo CLI
          npm install -g @expo/cli
          
          # Install dependencies with npm (more reliable than pnpm for Expo)
          npm install
          
          # Check project structure
          echo "Project files:"
          ls -la
          
      - name: Build Android APK
        script: |
          # Clear any existing builds
          rm -rf android
          
          # Generate Android project
          npx expo prebuild --platform android --clear
          
          # Build APK
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          
          # Copy APK to artifacts
          cd ..
          mkdir -p artifacts
          cp android/app/build/outputs/apk/debug/app-debug.apk artifacts/
          
          echo "Build complete:"
          ls -la artifacts/

    artifacts:
      - artifacts/*.apk
      
    publishing:
      email:
        recipients:
          - deamirclothingstores@gmail.com
        notify:
          success: true
          failure: true
          
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true