workflows:
  android-workflow:
    name: Android Build with Expo
    max_build_duration: 120
    environment:
      vars:
        KEYSTORE_PASSWORD: android
        KEY_ALIAS: androiddebugkey
        KEY_PASSWORD: android
      node: 18.17.1
    scripts:
      - name: Install dependencies & Expo CLI
        script: |
          npm install -g pnpm expo-cli
          pnpm install

      - name: Prebuild Android project
        script: |
          npx expo prebuild --clean --platform android

      - name: Build Android Release
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --stacktrace --info
          cd ..
          mkdir -p build
          cp android/app/build/outputs/apk/release/*.apk build/ 2>/dev/null || true
          cp android/app/build/outputs/bundle/release/*.aab build/ 2>/dev/null || true

    artifacts:
      - build/*.apk
      - build/*.aab

    publishing:
      email:
        recipients:
          - deamirclothingstores@gmail.com

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
