workflows:
  android-workflow:
    name: Android Build with Expo
    max_build_duration: 120
    environment:
      vars:
        KEYSTORE_PASSWORD: android
        KEY_ALIAS: androiddebugkey
        KEY_PASSWORD: android
      node: 18.17.1
    scripts:
      - name: Set up environment
        script: |
          # Install Node.js and pnpm
          npm install -g pnpm
          pnpm install
          
          # Install Expo CLI
          npm install -g expo-cli
          
          # Clear any cached files
          rm -rf $HOME/.expo
          rm -rf node_modules
          rm -rf $HOME/.gradle/caches
          
          # Clean install dependencies
          pnpm install --force

      - name: Build Android Release
        script: |
          # Clear previous build
          rm -rf android
          
          # Prebuild with expo
          npx expo prebuild --clean -p android
          
          # Navigate to android directory
          cd android
          
          # Clean Gradle
          ./gradlew clean
          
          # Create keystore properties
          echo "storeFile=debug.keystore" > app/keystore.properties
          echo "storePassword=android" >> app/keystore.properties
          echo "keyAlias=androiddebugkey" >> app/keystore.properties
          echo "keyPassword=android" >> app/keystore.properties
          
          # Update build.gradle files
          sed -i "s/compileSdk = 33/compileSdk = 33/" app/build.gradle
          sed -i "s/targetSdk = 33/targetSdk = 33/" app/build.gradle
          
          # Build the release
          ./gradlew assembleRelease --stacktrace
          
          # Move artifacts to build directory
          cd ..
          mkdir -p build
          cp android/app/build/outputs/bundle/release/app-release.aab build/
          cp android/app/build/outputs/apk/release/app-release.apk build/
    
    artifacts:
      - build/*.apk
      - build/*.aab
    
    publishing:
      email:
        recipients:
          - your.email@example.com
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true